import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          About(),
        ]),
      ),
    );
  }
}

class About extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 1111,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 23,
                top: 28,
                child: SizedBox(
                  width: 214,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Nama',
                          style: TextStyle(
                            color: Color(0xFFFF8E70),
                            fontSize: 24,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.48,
                          ),
                        ),
                        TextSpan(
                          text: ' ',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 24,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.48,
                          ),
                        ),
                        TextSpan(
                          text: 'App',
                          style: TextStyle(
                            color: Color(0xFF15131E),
                            fontSize: 24,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.48,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 66,
                top: 607,
                child: Container(
                  width: 226,
                  height: 374,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 42,
                        top: 0,
                        child: SizedBox(
                          width: 156,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: 'Tentang ',
                                  style: TextStyle(
                                    color: Color(0xFFFF8E70),
                                    fontSize: 24,
                                    fontFamily: 'Lato',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                    letterSpacing: 0.48,
                                  ),
                                ),
                                TextSpan(
                                  text: 'Kami',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 24,
                                    fontFamily: 'Lato',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                    letterSpacing: 0.48,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 46,
                        child: Container(
                          width: 100,
                          height: 100,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/100x100"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 219,
                        child: Container(
                          width: 100,
                          height: 100,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 126,
                        top: 219,
                        child: Container(
                          width: 100,
                          height: 100,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 126,
                        top: 46,
                        child: Container(
                          width: 100,
                          height: 100,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 7,
                        top: 160,
                        child: Text(
                          'Aulia Gondrong\n21111111',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 12,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.24,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 133,
                        top: 158,
                        child: Text(
                          'Aulia Gondrong\n21111111',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 12,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.24,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 7,
                        top: 346,
                        child: Text(
                          'Aulia Gondrong\n21111111',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 12,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.24,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 133,
                        top: 346,
                        child: Text(
                          'Aulia Gondrong\n21111111',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 12,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.24,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 95,
                child: Container(
                  width: 272,
                  height: 445.93,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 42,
                        top: 0,
                        child: SizedBox(
                          width: 186,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: 'Tentang ',
                                  style: TextStyle(
                                    color: Color(0xFFFF8E70),
                                    fontSize: 24,
                                    fontFamily: 'Lato',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                    letterSpacing: 0.48,
                                  ),
                                ),
                                TextSpan(
                                  text: 'Aplikasi',
                                  style: TextStyle(
                                    color: Color(0xFF15131E),
                                    fontSize: 24,
                                    fontFamily: 'Lato',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                    letterSpacing: 0.48,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 60,
                        top: 56,
                        child: Container(
                          width: 150,
                          height: 150,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD9D9D9),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 69,
                        top: 233,
                        child: Text.rich(
                          TextSpan(
                            children: [
                              TextSpan(
                                text: 'Cupang',
                                style: TextStyle(
                                  color: Color(0xFFFF8F71),
                                  fontSize: 16,
                                  fontFamily: 'Lato',
                                  fontWeight: FontWeight.w400,
                                  height: 0,
                                  letterSpacing: 0.32,
                                ),
                              ),
                              TextSpan(
                                text: ' Streaming',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 16,
                                  fontFamily: 'Lato',
                                  fontWeight: FontWeight.w400,
                                  height: 0,
                                  letterSpacing: 0.32,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 268,
                        child: Container(
                          width: 272,
                          height: 177.93,
                          decoration: ShapeDecoration(
                            color: Color(0x4CD9D9D9),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 1, color: Colors.white),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 170,
                        top: 394,
                        child: Text.rich(
                          TextSpan(
                            children: [
                              TextSpan(
                                text: 'Cup',
                                style: TextStyle(
                                  color: Color(0xFFFF8F71),
                                  fontSize: 10,
                                  fontFamily: 'Lato',
                                  fontWeight: FontWeight.w300,
                                  height: 0,
                                  letterSpacing: 0.20,
                                ),
                              ),
                              TextSpan(
                                text: 'ang',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 10,
                                  fontFamily: 'Lato',
                                  fontWeight: FontWeight.w300,
                                  height: 0,
                                  letterSpacing: 0.20,
                                ),
                              ),
                            ],
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                      Positioned(
                        left: 175,
                        top: 379,
                        child: Text(
                          'Devs',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 10,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.20,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 122,
                        top: 379,
                        child: Text(
                          'Size',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 10,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.20,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 117,
                        top: 396,
                        child: Text(
                          '1.5 Tb',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 10,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w300,
                            height: 0,
                            letterSpacing: 0.20,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 3,
                        top: 279,
                        child: SizedBox(
                          width: 264,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: 'Cupang Streaming',
                                  style: TextStyle(
                                    color: Color(0xFFFF8F71),
                                    fontSize: 12,
                                    fontFamily: 'Lato',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                    letterSpacing: 0.24,
                                  ),
                                ),
                                TextSpan(
                                  text: ' adalah platform digital yang memungkinkan pengguna untuk menonton konten audio dan video melalui internet. Pengguna dapat mengakses berbagai jenis konten, seperti film, dan Acara TV',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 12,
                                    fontFamily: 'Lato',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                    letterSpacing: 0.24,
                                  ),
                                ),
                              ],
                            ),
                            textAlign: TextAlign.center,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 15,
                        top: 374,
                        child: Container(
                          width: 240,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFFC9C9C9),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 15,
                        top: 414,
                        child: Container(
                          width: 240,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFFC9C9C9),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 66,
                        top: 379,
                        child: Text(
                          'Vers',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 10,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.20,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 65,
                        top: 396,
                        child: Text(
                          '0.0.1',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 10,
                            fontFamily: 'Lato',
                            fontWeight: FontWeight.w300,
                            height: 0,
                            letterSpacing: 0.20,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 104,
                        top: 381,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          child: Container(
                            width: 25,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 1,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                  color: Color(0xFFC1C1C1),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 158,
                        top: 381,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          child: Container(
                            width: 25,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 1,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                  color: Color(0xFFC1C1C1),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -8,
                top: 1027,
                child: Container(
                  width: 375,
                  height: 84,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 375,
                          height: 84,
                          decoration: BoxDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(0.00, -1.00),
                              end: Alignment(0, 1),
                              colors: [Color(0xFF15141F), Color(0x0014141F), Color(0xFF14141F)],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 14,
                        child: Container(
                          width: 375,
                          height: 70,
                          decoration: BoxDecoration(color: Color(0xFF15141F)),
                        ),
                      ),
                      Positioned(
                        left: 64,
                        top: 34.56,
                        child: Container(
                          width: 247.14,
                          height: 30.44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 2.44,
                                child: Container(
                                  width: 24.74,
                                  height: 26.04,
                                  child: Stack(children: [
                                  
                                  ]),
                                ),
                              ),
                              Positioned(
                                left: 225,
                                top: 0,
                                child: Container(
                                  width: 22.14,
                                  height: 26.57,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 22.14,
                                          height: 26.57,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 22.14,
                                                  height: 26.57,
                                                  child: Stack(children: [
                                                  
                                                  ]),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 109,
                                top: 0.44,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 30,
                                          height: 30,
                                          child: Stack(children: [
                                          
                                          ]),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}